logging:
  level:
    root: warn
    service: info
    org.zalando.logbook: trace

spring:
  application:
    name: security-spring-boot-verified-links
  jackson:
    default-property-inclusion: non_null
